[profile.default]
src = 'contracts'
out = 'out'
solc_version = '0.8.19'
optimizer_runs = 1000000
via_ir = false
libs = ['node_modules', 'foundry-lib']
test = 'test'
cache_path  = 'foundry-cache'
gas_reports = ["Governable", "CrossChainGovernableMock", "GuardableMock"]
bytecode_hash = "none"
ffi = false